# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created

name: Gradle publish GitHub Packages

on:
  release:
    types: [created]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Gradle
      run: gradle build
      env:
        GPR_USR: ${{ secrets.GPR_USR }}
        GPR_KEY: ${{ secrets.GPR_KEY }}

    - name: Publish to GitHub Packages
      run: gradle publish
      env:
        GPR_USR: ${{ secrets.GPR_USR }}
        GPR_KEY: ${{ secrets.GPR_KEY }}